### ISSUE TITLE
Removing set doesn't add back recipes removed by said set

### ISSUE THREAD

**Issue by Mohron** [legendblade/CraftingHarmonics#122]
Version: craftingharmonics-1.9.4-1.4.9.32.jar

On my server I added one of my custom sets which removes all TiC tool forges and only adds back only the Knightslime version. When I /ch removeSet, it removed the recipe I added but did not restore the recipes I had originally removed in the set.

**Comment by legendblade** [comment]
Huh.  That's... odd.

I'll take a look at it; I'm planning on releasing 1.5.0 today, if this is a quick fix, or I can easily determine the root cause, I will go ahead and push the fix with 1.5.0, and, if not, I'll try and get something in for 1.5.1.

Is this happening in a current version of your pack on Curse so I can download and test with the modlist and config, or is it in a separate / testing instance?

Thanks.

**Comment by Mohron** [comment]
Be my guest! :smile: 
http://minecraft.curseforge.com/projects/rebel-uprising

**Comment by legendblade** [comment]
Sorry, I just got around to testing this, and can't reproduce it (in SSP) with your config with CH1.5.0.  Are you still having this problem in recent versions?

Also, have you noticed if this is just on server, or in single-player as well?

Thanks.

**Comment by Mohron** [comment]
I honestly don't do much testing in SSP since my primary concern is server play.  I haven't gotten a chance to update my pack yet so I'll let you know if I still have the problem once I do.
