### ISSUE TITLE
Possible incorrect override of compareTo

### ISSUE THREAD

**Issue by Thiana** [legendblade/CraftingHarmonics#128]
```
 [com.matthewprenger.helpfixer.HelpFixer/HelpFixer]: Command [ch, org.winterblade.minecraft.harmony.commands.CommandHandler] incorrectly overrides compareTo: %s
```

This warning is issued by HelpFixer (http://minecraft.curseforge.com/projects/helpfixer?gameCategorySlug=mc-mods&projectID=223797) on both the 1.9.4 and 1.10.0 versions of CH.

**Comment by legendblade** [comment]
This line needs to be fixed to actually compare commands: https://github.com/legendblade/CraftingHarmonics/blob/master/src/main/java/org/winterblade/minecraft/harmony/commands/CommandHandler.java#L108

I'll need to look into how HelpFixer wants it used in order to actually know what they want returned.
